CREATE OR REPLACE FUNCTION GETPRODUCTSFROMORDER(order_identifier IN PURCHASEORDER.ID_ORDER%TYPE)
RETURN SYS_REFCURSOR AS

    result      SYS_REFCURSOR;

BEGIN

    OPEN result FOR

        SELECT * FROM PRODUCT
        INNER JOIN PRODUCTLINE ON PRODUCT.ID_PRODUCT = PRODUCTLINE.ID_PRODUCT
        INNER JOIN PURCHASEORDER ON PRODUCTLINE.ID_ORDER = order_identifier;

    RETURN result;
END;