CREATE OR REPLACE FUNCTION GETPHARMACYADDRESSES RETURN SYS_REFCURSOR IS

    result      SYS_REFCURSOR;

BEGIN
    OPEN result FOR

        SELECT A.* FROM ADDRESS A
        INNER JOIN PHARMACY P ON A.ADDRESS = P.ADDRESS;

    RETURN result;
END;